version: '2'
services:
  gabemaddex-mysql:
    container_name: gabemaddex-mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ../sites-databases/gabemaddex:/var/lib/mysql
    networks:
      - dockercompose
    command: mysqld --max_allowed_packet=64M
    restart: always
  gabemaddex:
    container_name: gabemaddex 
    image: codekoalas/drupal8
    environment:
      VIRTUAL_HOST: .gabemaddex.com
      GIT_REPO: https://github.com/gmaddex/drupal8-learner.git
      GIT_BRANCH: master
      MYSQL_SERVER: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      DRUPAL_BASE_URL: http://gabemaddex.com
      DRUPAL_TRUSTED_HOSTS: gabemaddex\.com$$
      DRUPAL_HTTPS: "off"
      APACHE_DOCROOT: /var/www/site/docroot
      PRODUCTION: "true"
      #SESMailHub: mail-relay.ckdev.io
      #LOCAL: "true"
    volumes:
      - ../sites-files/gabemaddex:/mnt/sites-files
      - ./:/var/www/site
    networks:
      - dockercompose
    links:
      - gabemaddex-mysql:mysql
    restart: always
networks:
  dockercompose:
    external:
      name: dockercompose_dockercompose
