version: '2'
services:
  drupal8-learner-mysql:
    container_name: drupal8-learner-mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ../sites-databases/drupal8-learner:/var/lib/mysql
    networks:
      - dockercompose
    command: mysqld --max_allowed_packet=64M
    restart: always
  drupal8-learner:
    container_name: drupal8-learner
    image: codekoalas/drupal8
    environment:
      VIRTUAL_HOST: .drupal8-learner.dev
      GIT_REPO: https://github.com/fabean/drupal8-learner.git
      GIT_BRANCH: master
      MYSQL_SERVER: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      DRUPAL_BASE_URL: http://drupal8-learner.dev
      DRUPAL_TRUSTED_HOSTS: drupal8-learner\.dev$$
      DRUPAL_HTTPS: "off"
      APACHE_DOCROOT: /var/www/site/docroot
      PRODUCTION: "false"
      SESMailHub: mail-relay.ckdev.io
      #LOCAL: "true"
    volumes:
      - ../sites-files/drupal8-learner:/mnt/sites-files
      - ./:/var/www/site
    networks:
      - dockercompose
    links:
      - drupal8-learner-mysql:mysql
    restart: always
networks:
  dockercompose:
    external:
      name: dockercompose_dockercompose
